import React from "react";
import { useHistory } from "react-router-dom";

// Lucide icons
import { ArrowLeft, Car, AlertTriangle, Gauge, TrendingUp, DollarSign, Download, FileText, Loader2 } from "lucide-react";

import jsPDF from "jspdf";

// core components
import GridContainer from "components/Grid/GridContainer.js";
import GridItem from "components/Grid/GridItem.js";
import Card from "components/Card/Card.js";
import CardBody from "components/Card/CardBody.js";
import Button from "components/CustomButtons/Button.js";

// hooks & utils
import { useFleetReport } from "hooks/useFleetReport";
import { formatDateOnly } from "types/database";

export default function FleetReport() {
  const history = useHistory();

  const { stats, loading } = useFleetReport();

  const handleExportCSV = () => {
    const csvContent = [
      ["Fleet Summary Report"],
      ["Generated", new Date().toLocaleString()],
      [""],
      ["Metric", "Value"],
      ["Total Vehicles", stats.totalVehicles],
      ["Active Vehicles", stats.activeVehicles],
      ["Total Distance (km)", stats.totalDistance],
      ["Total Service Cost (JMD)", `J$${stats.totalServiceCost.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
      ["Total DTCs", stats.totalDTCs],
      ["Driving Behavior Alerts", stats.totalBehaviorAlerts],
    ]
      .map(row => row.join(","))
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", `fleet-report-${new Date().toISOString().split("T")[0]}.csv`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = () => {
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    let y = 18;

    const primaryColor = [31, 41, 55]; // #1f2937
    const secondaryColor = [107, 114, 128]; // #6b7280
    const headerBlue = [59, 130, 246]; // #3B82F6
    const cardBorder = [229, 231, 235]; // #E5E7EB

    // Header
    pdf.setFillColor(...headerBlue);
    pdf.rect(0, 0, pageWidth, 30, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Fleet Summary Report", margin, 18);

    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin, 16, { align: "right" });
    pdf.text("Period: Last 24 hours", pageWidth - margin, 23, { align: "right" });

    y = 42;

    // Vehicle Information block
    pdf.setTextColor(...primaryColor);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Fleet Overview", margin, y);
    y += 6;

    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...secondaryColor);
    pdf.text("High-level performance and alert summary for your fleet.", margin, y);
    y += 10;

    // Stat cards
    const cardWidth = (pageWidth - margin * 2 - 10) / 3;
    const cardHeight = 26;

    const drawStatCard = (x, yPos, color, label, value) => {
      pdf.setDrawColor(...cardBorder);
      pdf.setFillColor(255, 255, 255);
      pdf.rect(x, yPos, cardWidth, cardHeight, "FD");
      pdf.setFillColor(...color);
      pdf.rect(x, yPos, cardWidth, 3, "F");
      pdf.setTextColor(...secondaryColor);
      pdf.setFontSize(8.5);
      pdf.text(label, x + 6, yPos + 12);
      pdf.setTextColor(...primaryColor);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(value, x + 6, yPos + 20);
      pdf.setFont("helvetica", "normal");
    };

    drawStatCard(margin, y, [16, 185, 129], "Active Vehicles", `${stats.activeVehicles}`);
    drawStatCard(margin + cardWidth + 5, y, [239, 68, 68], "Total Vehicles", `${stats.totalVehicles}`);
    drawStatCard(margin + (cardWidth + 5) * 2, y, [245, 158, 11], "Total Distance", `${stats.totalDistance} km`);

    y += cardHeight + 8;
    drawStatCard(margin, y, [99, 102, 241], "Total DTCs", `${stats.totalDTCs}`);
    drawStatCard(margin + cardWidth + 5, y, [59, 130, 246], "Behavior Alerts", `${stats.totalBehaviorAlerts}`);
    drawStatCard(margin + (cardWidth + 5) * 2, y, [5, 150, 105], "Total Service Cost", `J$${stats.totalServiceCost.toLocaleString("en-US", { minimumFractionDigits: 2 })}`);

    // Footer note
    const footerY = pageHeight - 12;
    pdf.setTextColor(...secondaryColor);
    pdf.setFontSize(8);
    pdf.text("Generated by Entry Fleet \u2022 Confidential", margin, footerY);

    pdf.save(`fleet-report-${new Date().toISOString().split("T")[0]}.pdf`);
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center py-20 px-5">
        <Loader2 className="animate-spin text-muted-foreground" size={40} />
      </div>
    );
  }

  return (
    <div className="print:p-0 print:m-0">
      {/* Print-only header */}
      <h1 className="hidden print:block text-[22px] font-bold mb-2 text-foreground">Fleet Summary Report</h1>
      <p className="hidden print:block text-xs text-muted-foreground mb-5">
        Generated: {new Date().toLocaleString()}
      </p>

      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 print:mb-4">
        <div className="flex items-center gap-3 md:gap-4">
          <Button
            className="bg-muted text-foreground p-2 min-w-[40px] rounded-lg hover:bg-muted print:hidden shrink-0"
            onClick={() => history.push("/admin/reports")}
          >
            <ArrowLeft size={20} />
          </Button>
          <div className="min-w-0">
            <h1 className="text-xl md:text-2xl font-semibold text-foreground m-0">Fleet Summary Report</h1>
            <p className="text-sm text-muted-foreground mt-1 mb-0">
              Overview of your entire fleet performance
            </p>
          </div>
        </div>
        <div className="flex gap-2 md:gap-3 print:hidden">
          <Button
            className="px-3 md:px-5 py-2 md:py-2.5 normal-case font-semibold rounded-lg shadow-sm bg-emerald-600 text-white hover:bg-emerald-700"
            onClick={handleExportCSV}
          >
            <Download className="mr-1.5 md:mr-2" size={16} />
            CSV
          </Button>
          <Button
            className="px-3 md:px-5 py-2 md:py-2.5 normal-case font-semibold rounded-lg shadow-sm bg-red-600 text-white hover:bg-red-700"
            onClick={handleExportPDF}
          >
            <FileText className="mr-1.5 md:mr-2" size={16} />
            PDF
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <GridContainer className="mb-8">
        <GridItem xs={12} sm={6} md={3}>
          <Card className="rounded-xl shadow-sm border border-border h-full print:shadow-none print:break-inside-avoid">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 bg-indigo-50">
                <Car size={24} className="text-indigo-600" />
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground mb-1 font-medium">Active Vehicles</p>
                <p className="text-[32px] font-bold text-foreground m-0 leading-tight">
                  {stats.activeVehicles}
                  <span className="text-sm text-muted-foreground font-medium ml-1">/ {stats.totalVehicles}</span>
                </p>
              </div>
            </CardBody>
          </Card>
        </GridItem>

        <GridItem xs={12} sm={6} md={3}>
          <Card className="rounded-xl shadow-sm border border-border h-full print:shadow-none print:break-inside-avoid">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 bg-emerald-50">
                <TrendingUp size={24} className="text-emerald-600" />
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground mb-1 font-medium">Total Distance</p>
                <p className="text-[32px] font-bold text-foreground m-0 leading-tight">
                  {stats.totalDistance.toLocaleString()}
                  <span className="text-sm text-muted-foreground font-medium ml-1">km</span>
                </p>
              </div>
            </CardBody>
          </Card>
        </GridItem>

        <GridItem xs={12} sm={6} md={3}>
          <Card className="rounded-xl shadow-sm border border-border h-full print:shadow-none print:break-inside-avoid">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 bg-red-50">
                <AlertTriangle size={24} className="text-red-600" />
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground mb-1 font-medium">Total DTCs</p>
                <p className="text-[32px] font-bold text-foreground m-0 leading-tight">{stats.totalDTCs}</p>
              </div>
            </CardBody>
          </Card>
        </GridItem>

        <GridItem xs={12} sm={6} md={3}>
          <Card className="rounded-xl shadow-sm border border-border h-full print:shadow-none print:break-inside-avoid">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 bg-amber-50">
                <Gauge size={24} className="text-amber-600" />
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground mb-1 font-medium">Behavior Alerts</p>
                <p className="text-[32px] font-bold text-foreground m-0 leading-tight">{stats.totalBehaviorAlerts}</p>
              </div>
            </CardBody>
          </Card>
        </GridItem>
      </GridContainer>

      {/* Service Cost Card */}
      <GridContainer style={{ marginBottom: "32px" }}>
        <GridItem xs={12} sm={6} md={4}>
          <Card className="rounded-xl shadow-sm border border-border h-full print:shadow-none print:break-inside-avoid">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0 bg-emerald-50">
                <DollarSign size={24} className="text-emerald-600" />
              </div>
              <div className="flex-1">
                <p className="text-sm text-muted-foreground mb-1 font-medium">Total Service Cost</p>
                <p className="text-[32px] font-bold text-foreground m-0 leading-tight">
                  J${stats.totalServiceCost.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  <span className="text-sm text-muted-foreground font-medium ml-1">JMD</span>
                </p>
              </div>
            </CardBody>
          </Card>
        </GridItem>
      </GridContainer>

      {/* Detailed Summary */}
      <GridContainer>
        <GridItem xs={12} md={8}>
          <Card className="rounded-xl shadow-sm border border-border print:shadow-none print:break-inside-avoid">
            <div className="px-4 md:px-6 py-4 md:py-5 border-b border-border flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <h3 className="text-base md:text-lg font-semibold text-foreground m-0">Detailed Summary</h3>
              <span className="text-xs md:text-[13px] text-muted-foreground px-3 md:px-4 py-1.5 md:py-2 bg-muted/50 rounded-md w-fit">
                Report generated: {formatDateOnly(new Date())}
              </span>
            </div>
            <CardBody className="p-6">
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Total Vehicles in Fleet</span>
                <span className="text-base text-foreground font-semibold">{stats.totalVehicles} vehicles</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Currently Active Vehicles</span>
                <span className="text-base text-foreground font-semibold">{stats.activeVehicles} vehicles</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Offline Vehicles</span>
                <span className="text-base text-foreground font-semibold">{stats.totalVehicles - stats.activeVehicles} vehicles</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Overall Distance Traveled</span>
                <span className="text-base text-foreground font-semibold">{stats.totalDistance.toLocaleString()} km</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Diagnostic Trouble Codes (DTCs)</span>
                <span className="text-base text-foreground font-semibold">{stats.totalDTCs} codes</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Driving Behavior Alerts</span>
                <span className="text-base text-foreground font-semibold">{stats.totalBehaviorAlerts} alerts</span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Total Service Cost</span>
                <span className="text-base text-foreground font-semibold">
                  J${stats.totalServiceCost.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} JMD
                </span>
              </div>
              <div className="flex justify-between items-center py-4">
                <span className="text-sm text-muted-foreground font-medium">Alert Types Included</span>
                <span className="text-base text-foreground font-semibold">Harsh Braking, Acceleration, Cornering, Overspeed</span>
              </div>
            </CardBody>
          </Card>
        </GridItem>

        <GridItem xs={12} md={4}>
          <Card className="rounded-xl shadow-sm border border-border print:shadow-none print:break-inside-avoid">
            <div className="px-6 py-5 border-b border-border flex items-center justify-between">
              <h3 className="text-lg font-semibold text-foreground m-0">Fleet Health</h3>
            </div>
            <CardBody className="p-6">
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Online Rate</span>
                <span className="text-base text-foreground font-semibold">
                  {stats.totalVehicles > 0
                    ? Math.round((stats.activeVehicles / stats.totalVehicles) * 100)
                    : 0}%
                </span>
              </div>
              <div className="flex justify-between items-center py-4 border-b border-border/50">
                <span className="text-sm text-muted-foreground font-medium">Avg DTCs per Vehicle</span>
                <span className="text-base text-foreground font-semibold">
                  {stats.totalVehicles > 0
                    ? (stats.totalDTCs / stats.totalVehicles).toFixed(1)
                    : 0}
                </span>
              </div>
              <div className="flex justify-between items-center py-4">
                <span className="text-sm text-muted-foreground font-medium">Avg Alerts per Vehicle</span>
                <span className="text-base text-foreground font-semibold">
                  {stats.totalVehicles > 0
                    ? (stats.totalBehaviorAlerts / stats.totalVehicles).toFixed(1)
                    : 0}
                </span>
              </div>
            </CardBody>
          </Card>
        </GridItem>
      </GridContainer>
    </div>
  );
}
